traducciones_origen_ingreso = {
    'Outras Receitas Correntes': 'Otras Receitas Corrientes',
    'Receita de Serviços': 'Ingresos por Servicios',
    'Transferências de Capital': 'Transferencias de Capital',
    'Alienação de Bens': 'Venta de Bienes',
    'Receita Agropecuária': 'Ingresos Agropecuarios',
    'Transferências Correntes': 'Transferencias Corrientes',
    'Receita Patrimonial': 'Ingresos Patrimoniales',
    'Impostos, Taxas e Contribuições de Melhoria': 'Impuestos, Tasas y Contribuciones de Mejoras',
    'Amortizações de Empréstimos': 'Amortización de Préstamos',
    'Contribuições': 'Contribuciones',
    'Receita Industrial': 'Ingresos Industriales',
    'Outras Receitas de Capital': 'Otros Ingresos de Capital',
    'Operações de Crédito': 'Operaciones de Crédito',
    'Sem informação': 'Sin información',
    'Receitas Correntes - a classificar': 'Ingresos Corrientes - por clasificar'
}
traducciones_tipo_ingreso= {
    'Bens, Direitos e Valores Incorporados ao Patr': 'Bienes, Derechos y Valores Incorporados al Patrimonio',
    'Indenizações, restituições e ressarcimentos': 'Indemnizaciones, restituciones y reembolsos',
    'Multas administrativas, contratuais e judicia': 'Multas administrativas, contractuales y judiciales',
    'Demais receitas correntes': 'Demás ingresos corrientes',
    'Receita de Serviços': 'Ingresos por Servicios',
    'Transferências de Instituições Privadas': 'Transferencias de Instituciones Privadas',
    'Alienação de bens móveis': 'Venta de bienes muebles',
    'Receita da produção animal e derivados': 'Ingresos de producción animal y derivados',
    'Transferências dos Municípios e de suas Entid': 'Transferencias de Municipios y sus Entidades',
    'Alienação de bens imóveis': 'Venta de bienes inmuebles',
    'Transferências de Pessoas Físicas': 'Transferencias de Personas Físicas',
    'Valores Mobiliários': 'Valores Mobiliarios',
    'Exploração do patrimônio imobiliário do Estad': 'Explotación del patrimonio inmobiliario del Estado',
    'Taxas': 'Tasas',
    'Outras receitas agropecuárias': 'Otros ingresos agropecuarios',
    'Delegação de Serviços Públicos Mediante Conce': 'Delegación de Servicios Públicos Mediante Concesión',
    'Amortizações de Empréstimos': 'Amortización de Préstamos',
    'Contribuições econômicas': 'Contribuciones económicas',
    'Transferências de Convênios': 'Transferencias de Convenios',
    'Receitas da indústria de transformação': 'Ingresos de la industria de transformación',
    'Contribuições sociais': 'Contribuciones sociales',
    'Receita dívida ativa alienação de estoques de': 'Ingresos de deuda activa por venta de inventarios',
    'Receita da produção vegetal': 'Ingresos de producción vegetal',
    'Receita dívida ativa proveniente de amortizaç': 'Ingresos de deuda activa provenientes de amortización',
    'Indenizações e restituições': 'Indemnizaciones y restituciones',
    'Exploração de recursos naturais': 'Explotación de recursos naturales',
    'Operações de crédito - mercado interno': 'Operaciones de crédito - mercado interno',
    'Cessão de direitos': 'Cesión de derechos',
    'Transferências de Outras Instituições Pública': 'Transferencias de Otras Instituciones Públicas',
    'Operações de crédito - mercado externo': 'Operaciones de crédito - mercado externo',
    'Demais receitas patrimoniais': 'Otros ingresos patrimoniales',
    'Impostos': 'Impuestos',
    'Resultado do Banco Central do Brasil': 'Resultado del Banco Central de Brasil',
    'Receitas decorrentes de aportes periódicos pa': 'Ingresos de aportes periódicos',
    'Sem informação': 'Sin información',
    'Receitas decorrentes de compensações ao Regim': 'Ingresos de compensaciones al Régimen',
    'Receita de concessões e permissões': 'Ingresos por concesiones y permisos',
    'Receita títulos do tesouro nacional resgatado': 'Ingresos de títulos del tesoro nacional rescatados',
    'Receitas Correntes - a classificar': 'Ingresos Corrientes - por clasificar',
    'Outras receitas': 'Otros ingresos',
    'Receitas de valores mobiliários': 'Ingresos de valores mobiliarios',
    'Transferências do Exterior': 'Transferencias del Exterior',
    'Transferências dos Estados e do Distrito Fede': 'Transferencias de los Estados y del Distrito Federal',
    'Integralização do capital social': 'Integralización del capital social',
    'Remuneração das Disponibilidades do Tesouro N': 'Remuneración de las Disponibilidades del Tesoro Nacional',
    'Serviços Administrativos e Comerciais Gerais': 'Servicios Administrativos y Comerciales Generales',
    'Outros serviços': 'Otros servicios',
    'Receita Agropecuária': 'Ingresos Agropecuarios',
    'Transferências Correntes': 'Transferencias Corrientes',
    'Transferências da União e de suas Entidades': 'Transferencias de la Unión y sus Entidades',
    'Receita Industrial': 'Ingresos Industriales',
    'Serviços e Atividades Financeiras': 'Servicios y Actividades Financieras',
    'Transferências de Capital': 'Transferencias de Capital',
    'Serviços e Atividades Referentes à Saúde': 'Servicios y Actividades Relacionadas con la Salud',
    'Serviços e Atividades Referentes à Navegação ': 'Servicios y Actividades Relacionadas con la Navegación',
    'Remuneração das Disponibilidades do Tesouro': 'Remuneración de las Disponibilidades del Tesoro',
    'Contribuições para Entidades Privadas de Serv': 'Contribuciones a Entidades Privadas de Servicio',
    'Alienação de bens intangíveis': 'Venta de bienes intangibles',
    'Resgate de Títulos do Tesouro': 'Rescate de Títulos del Tesoro',
    'Exploração do patrimônio intangível': 'Explotación del patrimonio intangible',
    'Transferências Provenientes de Depósito Não I': 'Transferencias Provenientes de Depósitos No Identificados',
    'Demais receitas de capital': 'Otros ingresos de capital'
}
